name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set Vercel Environment Variables
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          MONGOUSER: ${{secrets.MONGOUSER}}
          PASSWORD: ${{secrets.PASSWORD}}
          DBNAME: ${{secrets.DBNAME}}
          CLUSTER_APP_NAME: ${{secrets.CLUSTER_APP_NAME}}
          CLUSTER_URI: ${{secrets.CLUSTER_URI}}
        run: |
          echo "Injecting environment variables to project $PROJECT_ID on Vercel..."

          for VAR in MONGOUSER PASSWORD DBNAME CLUSTER_APP_NAME CLUSTER_URI; do
            VALUE=$(printenv $VAR)
            echo "Setting $VAR..."
            curl -X POST "https://api.vercel.com/v10/projects/$PROJECT_ID/env" \
              -H "Authorization: Bearer $VERCEL_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "key": "'"$VAR"'",
                "value": "'"$VALUE"'",
                "target": ["production"]
            }'
          done

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
          vercel build --prod --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
