name: Runner self-hosted test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Test command
        run: pwd
      - name: Update page
        run: git pull origin main
